[project]
name = "s3-etl-quarantine"
version = "0.1.0"
description = "Pulumi + Data X-Ray S3 quarantine automation"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pulumi",
    "pulumi-aws",
    "boto3",
    "python-dotenv",
    "dxrpy",
]
