services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: rag-postgres
    environment:
      POSTGRES_DB: ragapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./database/create_user.sql:/docker-entrypoint-initdb.d/02-create_user.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ragapp"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
